/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-dim': '#d9dadc',
        'outline-variant': '#d0c6ab',
        'tertiary-fixed-dim': '#f6be45',
        'on-background': '#1a1c1d',
        'surface-variant': '#e2e2e4',
        'on-secondary-fixed-variant': '#474747',
        'secondary-container': '#e2e2e2',
        'tertiary': '#7b5900',
        'surface-container': '#eeeef0',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-primary-container': '#705e00',
        'inverse-surface': '#2f3132',
        'on-secondary-container': '#646464',
        'surface-container-low': '#f3f3f5',
        'on-tertiary-fixed': '#261900',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface': '#f9f9fb',
        'primary-container': '#ffd700',
        'on-primary-fixed-variant': '#544600',
        'surface-container-high': '#e8e8ea',
        'secondary-fixed-dim': '#c6c6c6',
        'on-surface': '#1a1c1d',
        'on-primary': '#ffffff',
        'primary': '#705d00',
        'surface-tint': '#705d00',
        'error': '#ba1a1a',
        'primary-fixed': '#ffe16d',
        'inverse-on-surface': '#f0f0f2',
        'tertiary-container': '#ffd482',
        'primary-fixed-dim': '#e9c400',
        'on-tertiary-container': '#7b5900',
        'tertiary-fixed': '#ffdea4',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#5d4200',
        'inverse-primary': '#e9c400',
        'outline': '#7e775f',
        'surface-container-highest': '#e2e2e4',
        'on-surface-variant': '#4d4732',
        'background': '#f9f9fb',
        'secondary-fixed': '#e2e2e2',
        'surface-bright': '#f9f9fb',
        'on-primary-fixed': '#221b00',
        'secondary': '#5e5e5e',
        'on-secondary-fixed': '#1b1b1b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        unit: '8px',
        gutter: '16px',
        'stack-lg': '32px',
        'container-margin': '24px',
        'stack-md': '16px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 4px 12px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.08)',
        'nav': '0 -4px 12px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
};
